### ISSUE TITLE
Wotr event problems

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#98] opened 2014-12-06 00:28 UTC
From moddb;
"I have some problems in the ring campaing, the last history event after aragorn become king of gondor does not apear. Frodo event does not apear in mordor. Based on the sequence followed by previous versions."

**Comment by Lonhaldar** [comment] 2015-01-07 12:37
Can be caused by the NOT = { year = 11368 } in the starting condition of this event chain. Will try to see if removing it will fix it.

**Comment by Lonhaldar** [comment] 2015-04-08 13:30
Closing that, as i'm working on a new build of these events.

**Closed by Lonhaldar** 2015-04-08 13:30 UTC
Labels: bug, event
